// Mock data for Kapisio prototype
const KAPISIO_DATA = {
  user: {
    name: 'Ayaz Haşımoğlu',
    handle: 'hasimogluayaz',
    avatar: 'AY',
    avatarColor: '#0f4a8a',
    rank: 'Çaylak',
    rankIcon: '🥚',
    points: 100,
    streak: 4,
    nextRank: 'Düellocu',
    nextRankAt: 400,
  },
  todayScenario: {
    id: 's-today',
    date: '11 Mayıs',
    title: 'Pazar günü aile ziyaretinde, anneannenizin eski sevgilisiyle karşılaşınca, ona sarılmalı mı yoksa soğuk mu davranmalısın?',
    countdown: '02:17:20',
    answersCount: 247,
    duellosLive: 12,
    answered: true,
    yourAnswer: 'soğuk tabii ki',
    side: 'soguk', // soguk or sicak
    voteSplit: { sicak: 38, soguk: 62 },
  },
  trendingTopics: [
    { tag: '#aile',          count: '1.2k' },
    { tag: '#etik',          count: '892' },
    { tag: '#duygusal',      count: '654' },
    { tag: '#sosyalmedya',   count: '430' },
    { tag: '#felsefe',       count: '301' },
  ],
  // Feed cards — mix of scenarios + ongoing duels
  feed: [
    {
      id: 'f1', kind: 'scenario',
      mode: 'senaryo',
      author: { name: 'Topluluk', handle: 'kapisio', avatar: 'K', color: '#2a6cf0', verified: true },
      time: '2s',
      title: 'Sokakta gördüğün ünlü oyuncuya selam vermek mi, kendi yoluna gitmek mi?',
      preview: '“Selam vermek hem ona hem sana iyi gelir, ama özelliğine de saygı şart…”',
      stats: { answers: 312, votes: 1240, fire: 89 },
      vote: { up: 412, down: 28, percent: 71 },
    },
    {
      id: 'f2', kind: 'duel',
      mode: 'tartisma',
      author: { name: 'Ela Hasımoglu', handle: 'elahas', avatar: 'E', color: '#1f8df0' },
      vs:     { name: 'Mert Y.',      handle: 'mertyy', avatar: 'M', color: '#2a6cf0' },
      time: '14d kaldı',
      title: 'Yapay zekayla yapılan sohbetler “gerçek” bir arkadaşlık sayılır mı?',
      stats: { answers: 0, votes: 89, fire: 41 },
      side: 'oylaniyor',
    },
    {
      id: 'f3', kind: 'scenario',
      mode: 'emoji',
      author: { name: 'Cesur', handle: 'cesurr', avatar: 'C', color: '#1c2f6e' },
      time: '6s',
      title: 'Sevgilinin eski fotoğraflarını gizlice gördüğünde ne hissediyorsun? — Sadece emoji ile cevapla.',
      preview: '😶‍🌫️ 🥲 🔥 👀',
      stats: { answers: 188, votes: 904, fire: 56 },
      vote: { up: 220, down: 12, percent: 81 },
    },
    {
      id: 'f4', kind: 'scenario',
      mode: 'karakter',
      author: { name: 'Zeynep Ak', handle: 'zeynepak', avatar: 'Z', color: '#1442a8' },
      time: '1g',
      title: 'Bir Hogwarts profesörü olsaydın, öğrencini sınavda kopya çekerken yakaladığında ne derdin?',
      preview: '“On puan eksi… ama önce nedenini söyle.” — Prof. McGonagall vibe',
      stats: { answers: 422, votes: 2100, fire: 134 },
      vote: { up: 1280, down: 89, percent: 93 },
    },
    {
      id: 'f5', kind: 'duel',
      mode: 'tartisma',
      author: { name: 'Sen', handle: 'hasimogluayaz', avatar: 'AY', color: '#0f4a8a' },
      vs:     { name: 'Cesur',  handle: 'cesurr',     avatar: 'C',  color: '#1c2f6e' },
      time: '3d kaldı',
      title: 'Pazar günü aile ziyaretinde, anneannenizin eski sevgilisiyle…',
      stats: { answers: 0, votes: 42, fire: 18 },
      side: 'oylaniyor',
    },
  ],
  // Answers on today's scenario detail screen
  answers: [
    {
      id: 'a1', author: { name: 'Mert Y.', handle: 'mertyy', avatar: 'M', color: '#2a6cf0', rank: 'Usta', rankIcon: '🏆' },
      side: 'sicak', time: '18d',
      body: 'Sarılırım. O bir misafir, ister eski sevgili olsun ister bir komşu — anneannemin geçmişine saygım var. Soğuk davranmak hem ona hem anneannenin sahip olduğu güzel anılara haksızlık.',
      votes: { up: 1284, down: 92, score: 1192 },
      replies: 34, gilded: true,
    },
    {
      id: 'a2', author: { name: 'Ela Hasımoglu', handle: 'elahas', avatar: 'E', color: '#1f8df0', rank: 'Düellocu', rankIcon: '⚔️' },
      side: 'soguk', time: '42d',
      body: 'Soğuk davranmak değil ama mesafeli olmak şart. Anneannemin yıllar önce aşıp gittiği bir adam, neden onu tekrar hayatımıza buyur edelim?',
      votes: { up: 892, down: 121, score: 771 },
      replies: 28,
    },
    {
      id: 'a3', author: { name: 'Cesur', handle: 'cesurr', avatar: 'C', color: '#1c2f6e', rank: 'Çaylak', rankIcon: '🥚' },
      side: 'soguk', time: '1s',
      body: 'soğuk tabii ki. uzatma.',
      votes: { up: 412, down: 88, score: 324 },
      replies: 11,
    },
    {
      id: 'a4', author: { name: 'Zeynep Ak', handle: 'zeynepak', avatar: 'Z', color: '#1442a8', rank: 'Şampiyon', rankIcon: '👑' },
      side: 'sicak', time: '2s',
      body: 'Sarılırım ama kısa keserim. Bir el sıkışmadan biraz fazla, bir kucaklaşmadan biraz az. Anneannem öyle isterdi — kibarlık ailenin imzasıdır.',
      votes: { up: 308, down: 24, score: 284 },
      replies: 9,
    },
  ],
  leaderboard: [
    { rank: 1, name: 'Zeynep Ak',      handle: 'zeynepak', avatar:'Z', color:'#1442a8', points: 18420, delta: '+2', badge: '👑' },
    { rank: 2, name: 'Mert Y.',        handle: 'mertyy',   avatar:'M', color:'#2a6cf0', points: 16280, delta: '+1', badge: '🏆' },
    { rank: 3, name: 'Ela Hasımoglu',  handle: 'elahas',   avatar:'E', color:'#1f8df0', points: 15940, delta: '-2', badge: '🏆' },
    { rank: 4, name: 'Burak Demir',    handle: 'burakd',   avatar:'B', color:'#4aa8ff', points: 12010, delta: '0',  badge: '⚔️' },
    { rank: 5, name: 'Lara K.',        handle: 'larak',    avatar:'L', color:'#2a6cf0', points:  9840, delta: '+4', badge: '⚔️' },
    { rank: 6, name: 'Cesur',          handle: 'cesurr',   avatar:'C', color:'#1c2f6e', points:  6210, delta: '-1', badge: '⚔️' },
  ],
  notifications: [
    { id:'n1', kind:'duel',     time:'12d',  who:'Ela Hasımoglu',  text:'seni düelloya çağırdı', target:'Pazar günü aile ziyaretinde…' },
    { id:'n2', kind:'vote',     time:'1s',   who:'Mert Y.',         text:'cevabını oyladı (+1)',  target:'soğuk tabii ki' },
    { id:'n3', kind:'badge',    time:'3s',   who:'Sistem',          text:'Yeni rozet: 3 günlük seri 🔥' },
    { id:'n4', kind:'follow',   time:'1g',   who:'Cesur',           text:'seni takip etmeye başladı' },
    { id:'n5', kind:'mention',  time:'2g',   who:'Zeynep Ak',       text:'cevabında senden bahsetti', target:'“…@hasimogluayaz haklı aslında”' },
    { id:'n6', kind:'vote',     time:'2g',   who:'4 kişi',           text:'cevabını oyladı (+4)',  target:'soğuk tabii ki' },
  ],
  discoverCats: [
    { id:'aile',     emoji:'🏠', label:'Aile',          count:'1.2k senaryo', color:'#2a6cf0' },
    { id:'iliski',   emoji:'💔', label:'İlişki',        count:'2.8k senaryo', color:'#1f8df0' },
    { id:'is',       emoji:'💼', label:'İş Hayatı',    count:'940 senaryo',  color:'#0f4a8a' },
    { id:'etik',     emoji:'⚖️', label:'Etik',          count:'612 senaryo',  color:'#1442a8' },
    { id:'felsefe',  emoji:'🧠', label:'Felsefe',       count:'480 senaryo',  color:'#16a34a' },
    { id:'gundem',   emoji:'📰', label:'Gündem',        count:'1.4k senaryo', color:'#1c2f6e' },
    { id:'ask',      emoji:'❤️', label:'Aşk',           count:'3.2k senaryo', color:'#dc2626' },
    { id:'arkadas',  emoji:'👥', label:'Arkadaşlık',    count:'860 senaryo',  color:'#4aa8ff' },
  ],
};

const MODE_INFO = {
  senaryo:  { label:'Senaryo',  emoji:'📝', color:'var(--k-mode-senaryo)' },
  emoji:    { label:'Emoji',    emoji:'😀', color:'var(--k-mode-emoji)' },
  karakter: { label:'Karakter', emoji:'🎭', color:'var(--k-mode-karakter)' },
  tartisma: { label:'Tartışma', emoji:'🔥', color:'var(--k-mode-tartisma)' },
};

window.KAPISIO_DATA = KAPISIO_DATA;
window.MODE_INFO = MODE_INFO;
